# Define input variables for the workspace
#  - non-sensitive variables can be added to 'staging.auto.tfvars'
#  - sensitive variables (passwords) should be set from the Terraform 
#    Cloud 'Variables' tab

variable "azure_secret" {
  type = object({
    tenant_id       = string
    subscription_id = string
    client_id       = string
    client_secret   = string
  })
}

variable "auth0_usermgt_secret" {
  type = object({
    domain        = string
    client_id     = string
    client_secret = string
  })
  description = "Auth0 user management API"
}

variable "datazoo_secret" {
  type = object({
    password_test = string
    password_live = string
  })
  description = "Data Zoo API"
}

variable "stripe_secret" {
  type = object({
    stripe_key          = string
    cust_webhook_secret = string
    subn_webhook_secret = string
  })
  description = "Stripe key"
}

variable "aws_secret" {
  type = object({
    access_key = string
    secret_key = string
  })
  description = "aws API credentials"
}

variable "circleci_secret" {
  type        = string
  description = "CircleCI API token"
}

variable "ghcr_secret" {
  type = object({
    server   = string
    username = string
    password = string
    email    = string
  })
  description = "GitHub container registry"
}

variable "launchdarkly_secret" {
  type        = string
  description = "Launch Darkly SDK key"
}

variable "optimizely_secret" {
  type        = string
  description = "Optimizely API key"
}

variable "ip_addresses" {
  type = map(string)
}

variable "elastic_console_secret" {
  type        = string
  description = "Elastic cloud console credentials"
}

variable "mongodb_secret" {
  type = object({
    org           = string
    public_key    = string
    private_key   = string
    app_user      = string
    app_password  = string
    data_user     = string
    data_password = string
  })
  description = "MongoDB Atlas keys and admin user"
}

variable "mixpanel_secret" {
  type = object({
    user   = string
    secret = string
  })
  description = "Mixpanel service account"
}

variable "auth0_terraform_secret" {
  type = object({
    domain        = string
    client_id     = string
    client_secret = string
  })
  description = "Authenticate with auth0 tenant"
}

variable "activecampaign_secret" {
  type        = string
  description = "API token generated by service account"
}

variable "zerossl_secret" {
  type = object({
    key_id   = string
    hmac_key = string
  })
}
