collections:
  - name: kyccertifier
    audit: true
    indexes:
      - name: tenant
        keys:
          - field: tenant
            type: asc
      - name: personId
        unique: true
        keys:
          - field: tenant
            type: asc
          - field: person.id
            type: asc
      - name: fullText
        keys:
          - field: person.givenNames
            type: text
          # - field: kyccertifier.middleName
          #   type: text
          - field: person.familyName
            type: text
          - field: person.birthDate
            type: text
          - field: person.addressLine1
            type: text
          - field: person.addressLine2
            type: text
          - field: person.suburb
            type: text
          - field: person.city
            type: text
          - field: person.region
            type: text
          - field: person.country
            type: text
